### ISSUE TITLE
GUI Example: Focus + Geo intents => one good viz & one empty viz

### ISSUE THREAD

**Issue by vsetlur** [tableau/vail#4]
Repro steps:
1. Add a focus intent, followed by distribution, and then geographic
2. Remove distribution - a vacuous viz appears alongside the highlighted bar chart

<img width="916" alt="Screen Shot 2021-05-12 at 2 48 18 PM" src="https://user-images.githubusercontent.com/1739257/118053934-427e9880-b33a-11eb-8aff-3c99f3a6e11b.png">

<img width="855" alt="Screen Shot 2021-05-12 at 2 48 40 PM" src="https://user-images.githubusercontent.com/1739257/118053926-3f83a800-b33a-11eb-87c8-063771144458.png">

**Comment by loki3** [comment]
More targeted repro steps:
1. Pick the covid data set
2. Add a focus intent, with {Field: "county", Adjective: "high"}
3. Add a geographic intent

Result: One reasonable bar chart, and one bar chart without the bars

**Comment by loki3** [comment]
The bug is in the interplay between field variables and the code that shapes the data. The system creates an output spec with one field var for the x encoding, which comes from the geographic intent, and one field var for the sort, which comes from the focus intent.

VizGallery.vizPerVarValue creates a FieldResolver for each viz it wants to make & tells them to resolve to different values of the variable, but this is only used for the first of the field variables. Then in sortData, when it shapes the data (sort, aggregate, select), it doesn't include the field that the other field variable resolves to. The end result is that the viz it generates wants data for a field that isn't included in the final data.

**Comment by loki3** [comment]
Fixed the query problem that lead to the second viz being empty.

However, the second viz isn't sorted as expected due to issue #6
